BEGIN TRANSACTION;
CREATE TABLE "Users" (
	`DiscordID`	INTEGER NOT NULL UNIQUE,
	`RFuel`	TEXT NOT NULL DEFAULT 100,
	`RAmmo`	INTEGER NOT NULL DEFAULT 100,
	`RSteel`	INTEGER NOT NULL DEFAULT 100,
	`RBauxite`	INTEGER NOT NULL DEFAULT 100,
	`Last_Bonus`	INTEGER NOT NULL DEFAULT 0,
	`TotalXP`	TEXT NOT NULL DEFAULT 0,
	`Inventory_Size`	INTEGER NOT NULL DEFAULT 150,
	`Last_Drop`	INTEGER NOT NULL DEFAULT 0,
	`Last_Craft`	INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY(`DiscordID`)
);
CREATE TABLE "INV_BASIC" (
	`ID`	INTEGER NOT NULL DEFAULT 0 PRIMARY KEY AUTOINCREMENT UNIQUE,
	`ShipID`	INTEGER NOT NULL,
	`ShipLevel`	INTEGER NOT NULL DEFAULT 1
);
COMMIT;
